export const logoMenuPositionMap = {
	// LogoPosition-NavigationPosition
	'left-left': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '1/2',
		menuColumn: '2/3',
		templateColumns: 'minmax(var(--logo-width), auto) 1fr',
		mTemplateColumns: 'minmax(var(--m-logo-width, var(--logo-width)), auto) 1fr',
	},
	'left-right': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '1/2',
		menuColumn: '2/3',
		templateColumns: 'minmax(var(--logo-width), auto) 1fr',
		mTemplateColumns: 'minmax(var(--m-logo-width, var(--logo-width)), auto) 1fr',
	},
	'left-center': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '1/2',
		menuColumn: '2/3',
		templateColumns: 'minmax(var(--logo-width), 1fr) auto 1fr',
		mTemplateColumns: 'minmax(var(--m-logo-width, var(--logo-width)), 1fr) auto 1fr',
	},
	'center-left': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '2/3',
		menuColumn: '1/2',
		templateColumns: '1fr minmax(var(--logo-width), auto) 1fr',
		mTemplateColumns: '1fr minmax(var(--m-logo-width, var(--logo-width)), auto) 1fr',
	},
	'center-right': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '2/3',
		menuColumn: '3/4',
		templateColumns: '1fr minmax(var(--logo-width), auto) 1fr',
		mTemplateColumns: '1fr minmax(var(--m-logo-width, var(--logo-width)), auto) 1fr',
	},
	'center-center': {
		logoRow: '1/2',
		menuRow: '2/3',
		logoColumn: '2/3',
		menuColumn: '1/4',
		templateColumns: '1fr minmax(var(--logo-width), auto) 1fr',
		mTemplateColumns: '1fr minmax(var(--m-logo-width, var(--logo-width)), auto) 1fr',
	},
	'right-left': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '2/3',
		menuColumn: '1/2',
		templateColumns: '1fr minmax(var(--logo-width), auto)',
		mTemplateColumns: '1fr minmax(var(--m-logo-width, var(--logo-width)), auto)',
	},
	'right-right': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '2/3',
		menuColumn: '1/2',
		templateColumns: '1fr minmax(var(--logo-width), auto)',
		mTemplateColumns: '1fr minmax(var(--m-logo-width, var(--logo-width)), auto)',
	},
	'right-center': {
		logoRow: '1/2',
		menuRow: '1/2',
		logoColumn: '3/4',
		menuColumn: '2/3',
		templateColumns: '1fr auto minmax(var(--logo-width), 1fr)',
		mTemplateColumns: '1fr auto minmax(var(--m-logo-width, var(--logo-width)), 1fr)',
	},
};
